spring:
  application:
    name: freeverse-backend
  profiles:
    active: dev
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080
  error:
    include-message: always
    include-binding-errors: always
